name: kalm
description: One Stop Solution for Your Mental Health.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  textfield_tags: ^1.4.2
  iconsax: ^0.0.8
  audioplayers: ^0.20.1
  google_fonts: ^2.1.0
  flutter_bloc: ^7.3.0
  tflite_flutter: ^0.9.0
  image_picker: ^0.8.4+2
  tflite_flutter_helper: ^0.3.0
  card_swiper: ^1.0.4
  speech_to_text: ^5.1.1
  dotted_line: ^3.0.1
  fl_chart: ^0.40.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/picture/
    - assets/font/
    - assets/ml_model/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Regular.ttf
        - asset: assets/font/Montserrat-Italic.ttf
          style: italic
        - asset: assets/font/Montserrat-Medium.ttf
        - asset: assets/font/Montserrat-MediumItalic.ttf
          style: italic
        - asset: assets/font/Montserrat-SemiBold.ttf
        - asset: assets/font/Montserrat-SemiBoldItalic.ttf
          style: italic
        - asset: assets/font/Montserrat-Bold.ttf
        - asset: assets/font/Montserrat-BoldItalic.ttf
          style: italic
