name: kalm
description: One Stop Solution for Your Mental Health.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+1-dev
environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  app_settings: ^4.1.4
  audioplayers: ^1.0.1
  cached_network_image: ^3.1.0
  card_swiper: ^2.0.4
  cupertino_icons: ^1.0.3
  dartz: ^0.10.1
  dio: ^4.0.6
  dotted_line: ^3.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.0.3
  fl_chart: ^0.55.0
  freezed: ^2.0.0
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.0
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  json_annotation: ^4.6.0
  path_provider: ^2.0.2
  retrofit: ^3.0.1+1
  retrofit_generator: any
  speech_to_text: ^5.6.0
  supabase: ^0.3.6
  supabase_flutter: ^0.3.3
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.0


dev_dependencies:
  build_runner: any
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.1.0
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/kalm_launcher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/kalm_launcher_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/picture/
    - assets/font/
    - assets/ml_model/

  fonts:
    - family: iconsax
      fonts:
        - asset: assets/font/iconsax.ttf
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Regular.ttf
        - asset: assets/font/Montserrat-Italic.ttf
          style: italic
        - asset: assets/font/Montserrat-Medium.ttf
        - asset: assets/font/Montserrat-MediumItalic.ttf
          style: italic
        - asset: assets/font/Montserrat-SemiBold.ttf
        - asset: assets/font/Montserrat-SemiBoldItalic.ttf
          style: italic
        - asset: assets/font/Montserrat-Bold.ttf
        - asset: assets/font/Montserrat-BoldItalic.ttf
          style: italic
